// <auto-generated />
namespace Vegallo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class vegDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vegDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201303060000252_vegDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
